// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SysJaky_N.Data;

#nullable disable

namespace SysJaky_N.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251604120000_AddPrivacyConsentAndRetention")]
    partial class AddPrivacyConsentAndRetention
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new Snapshot().Build(modelBuilder);
        }

        private sealed class Snapshot : ApplicationDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}
